language: python
python:
  - "3.8"
  # - "weekly"  # weekly build
  # - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest --cov=./dassh tests/
after_success:
  - codecov

