language: python
python:
  - "3.8"
  # - "weekly"  # weekly build
  # - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/

