name: CI

on:
# Triggers the workflow on push or pull request events for the master/develop branches
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  # Allows us to run this workflow manually
  workflow_dispatch:

jobs:

  python-3.6:
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        python-version: 3.6
          os:
            -   name: Linux
                runs-on: ubuntu-20.04
                python_platform: linux
            #-   name: Windows
            #    runs-on: windows-latest
            #    python_platform: win32
            -   name: macOS
                runs-on: macos-latest
                python_platform: darwin
    name: "Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Package setup
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Package tests
        shell: bash
        run: pytest --cov=./dassh ./tests/ --cov-report xml:coverage_${{ matrix.python-version }}.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          files: coverage_${{ matrix.python-version }}.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  python-3.7+:
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      matrix:
        python-version: [3.6]
          os:
            -   name: Linux
                runs-on: ubuntu-latest
                python_platform: linux
            #-   name: Windows
            #    runs-on: windows-latest
            #    python_platform: win32
            -   name: macOS
                runs-on: macos-latest
                python_platform: darwin
    name: "Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Package setup
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Package tests
        shell: bash
        run: pytest --cov=./dassh ./tests/ --cov-report xml:coverage_${{ matrix.python-version }}.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          files: coverage_${{ matrix.python-version }}.xml
          token: ${{ secrets.CODECOV_TOKEN }}
